---
# all non secret vars - for secrets check ansible vault https://docs.ansible.com/ansible/latest/vault_guide/index.html

usergroups:
  - users
  - admins

dockerusers:
  - {name: 'administrator', groups: 'docker'}

users:
  - {name: 'administrator', groups: 'users, admins'}
#   - {name: 'otheruser', groups: 'users', smbpasswd: 'otheruser'}
#   - {name: 'thirduser', groups: 'users', smbpasswd: 'thirduser'}
#   - {name: 'userNotInGroups', groups: '', smbpasswd: 'userNotInGroups'}

# domain_name: example.com

adminuser: administrator # should be an existing one from above
docker: {
  external_network: docker_ext,
  data_dir: '/dataPool/docker/data',
  # data for docker env
  PUID: '1000',
  PGID: '115'
}
