---
- name: Ensure usergroups exist
  group:
    name: "{{item}}"
    state: present
  with_items:
    "{{usergroups}}"

- name: Create users
  user:
    name: "{{item.name}}"
    groups: "{{item.groups}}"
    append: yes
    update_password: on_create
  with_items:
    "{{users}}"